name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/dbt-command-center
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      packages: write
      contents: write
      deployments: write
    steps:
      # retrieve your distributions here
      - uses: actions/checkout@v4.1.6
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Install npm dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd web
          npm ci
          cd ..
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Build package
        run: |
          rm -rf dist
          cd web
          npm run build
          cd .. 
          python setup.py sdist bdist_wheel
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
